import Head from "next/head";

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>Front-End Mentor Challenge || Next JS Article </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <div className="mx-auto md:flex md:w-3/5 md:flex-row md:h-auto">
        <img
          src="/images/drawers.jpg"
          alt=""
          className="rounded-tr-md rounded-tl-md md:h-auto md:w-2/5 md:rounded-bl-md md:rounded-tr-none h-48 w-full"
        />
        <div className="bg-white p-8 rounded-br-md rounded-bl-md md:rounded-bl-none text-gray-500">
          <div className="font-semibold text-gray-700">
            Shift the overall look and feel by adding these wonderful touches to
            furniture in your home
          </div>
          <div className="text-sm text-gray-600 mt-4">
            Ever been in a room and felt like something was missing? Perhaps it
            felt slightly bare and uninviting. I’ve got some simple tips to help
            you make any room feel complete.
          </div>
          <div className="flex justify-between mt-8">
            <div className="flex justify-between gap-x-1">
              <img
                src="/images/avatar-michelle.jpg"
                className="rounded-full h-12"
                alt=""
              />
              <div className='ml-2'>
                <p className="text-gray-700 font-bold text-sm">
                  Michelle Appleton
                </p>
                <p className="text-gray-400 text-sm"> 28 Jun 2020</p>
              </div>
            </div>
            <div className="rounded-full bg-gray-300 h-10 w-10">
              <img src="/images/icon-share.svg" className="mx-auto p-2 h-9" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
